/******************************************************************************
 * AUTO-GENERATED FILE — DO NOT EDIT
 *
 * Generated by: python -m ramulator codegen
 * Source:       python/ramulator/dram/lpddr6pim.py
 *
 * Regenerate:   python -m ramulator codegen LPDDR6PIM
 ******************************************************************************/
#include "ramulator/dram/commands/ACT1.h"
#include "ramulator/dram/commands/ACT2.h"
#include "ramulator/dram/commands/CAS.h"
#include "ramulator/dram/commands/HAB.h"
#include "ramulator/dram/commands/HAB_PIM.h"
#include "ramulator/dram/commands/PIM_BCAST.h"
#include "ramulator/dram/commands/PIM_MAC.h"
#include "ramulator/dram/commands/PIM_MAC_AB.h"
#include "ramulator/dram/commands/PREab.h"
#include "ramulator/dram/commands/PREpb.h"
#include "ramulator/dram/commands/RDA_L.h"
#include "ramulator/dram/commands/RDA_S.h"
#include "ramulator/dram/commands/RD_L.h"
#include "ramulator/dram/commands/RD_S.h"
#include "ramulator/dram/commands/REFab.h"
#include "ramulator/dram/commands/SB.h"
#include "ramulator/dram/commands/WRA_L.h"
#include "ramulator/dram/commands/WRA_S.h"
#include "ramulator/dram/commands/WR_L.h"
#include "ramulator/dram/commands/WR_S.h"
#include "ramulator/dram/commands/populate.h"
#include "ramulator/dram/dram_spec.h"

namespace Ramulator {

class LPDDR6PIM : public DRAMSpec {
 public:
  struct Level {
    enum : int { Channel, Rank, BankGroup, Bank, Row, Column, COUNT };
  };
  struct Command {
    enum : int {
      ACT1,
      ACT2,
      PREpb,
      PREab,
      CAS,
      RD_S,
      WR_S,
      RDA_S,
      WRA_S,
      RD_L,
      WR_L,
      RDA_L,
      WRA_L,
      REFab,
      SB,
      HAB,
      HAB_PIM,
      PIM_BCAST,
      PIM_MAC,
      PIM_MAC_AB,
      COUNT
    };
  };
  struct State {
    enum : int { Opened, Closed, Activating, N_A, PIM_SB, PIM_HAB, PIM_HAB_PIM, COUNT };
  };
  struct Timing {
    enum : int {
      rate,
      nBL_min,
      nBL_max,
      nBL_min_L,
      nBL_max_L,
      nRL,
      nWL,
      nACU,
      nRCDr,
      nRCDw,
      nRP,
      nRPab,
      nRAS,
      nRC,
      nWTP,
      nRTP,
      nRTP_L,
      nPPD,
      nCCDS,
      nCCDL,
      nCCDL_L,
      nCCDS_WR,
      nCCDL_WR,
      nCCDL_WR_L,
      nRRD,
      nWTRS,
      nWTRL,
      nRTW_S,
      nRTW_L,
      nRTW_S_L,
      nRTW_L_L,
      nWCK2DQO,
      nRPST,
      nODTLon,
      nODTon_min,
      nFAW,
      nRFC,
      nREFI,
      nWCKPST,
      nCAS,
      nAAD,
      nCS,
      tCK_ps,
      nPIM_MAC_LAT,
      nPIM_MAC_II,
      COUNT
    };
  };

  using CommandImpls =
      std::tuple<Cmd::ACT1<LPDDR6PIM>, Cmd::ACT2<LPDDR6PIM>, Cmd::PREpb<LPDDR6PIM>, Cmd::PREab<LPDDR6PIM>,
                 Cmd::CAS<LPDDR6PIM>, Cmd::RD_S<LPDDR6PIM>, Cmd::WR_S<LPDDR6PIM>, Cmd::RDA_S<LPDDR6PIM>,
                 Cmd::WRA_S<LPDDR6PIM>, Cmd::RD_L<LPDDR6PIM>, Cmd::WR_L<LPDDR6PIM>, Cmd::RDA_L<LPDDR6PIM>,
                 Cmd::WRA_L<LPDDR6PIM>, Cmd::REFab<LPDDR6PIM>, Cmd::SB<LPDDR6PIM>, Cmd::HAB<LPDDR6PIM>,
                 Cmd::HAB_PIM<LPDDR6PIM>, Cmd::PIM_BCAST<LPDDR6PIM>, Cmd::PIM_MAC<LPDDR6PIM>,
                 Cmd::PIM_MAC_AB<LPDDR6PIM> >;

  LPDDR6PIM(const ConfigNode& config) {
    // Counts
    level_count = Level::COUNT;
    command_count = Command::COUNT;
    state_count = State::COUNT;
    timing_count = Timing::COUNT;

    // String name maps + reverse lookup vectors
    set_names(levels, level_names, {"Channel", "Rank", "BankGroup", "Bank", "Row", "Column"});
    set_names(commands, command_names,
              {"ACT1", "ACT2",  "PREpb", "PREab", "CAS", "RD_S", "WR_S",    "RDA_S",     "WRA_S",   "RD_L",
               "WR_L", "RDA_L", "WRA_L", "REFab", "SB",  "HAB",  "HAB_PIM", "PIM_BCAST", "PIM_MAC", "PIM_MAC_AB"});
    set_names(states, state_names, {"Opened", "Closed", "Activating", "N_A", "PIM_SB", "PIM_HAB", "PIM_HAB_PIM"});
    set_names(timings, timing_names,
              {"rate",   "nBL_min", "nBL_max",    "nBL_min_L",    "nBL_max_L",  "nRL",      "nWL",      "nACU",
               "nRCDr",  "nRCDw",   "nRP",        "nRPab",        "nRAS",       "nRC",      "nWTP",     "nRTP",
               "nRTP_L", "nPPD",    "nCCDS",      "nCCDL",        "nCCDL_L",    "nCCDS_WR", "nCCDL_WR", "nCCDL_WR_L",
               "nRRD",   "nWTRS",   "nWTRL",      "nRTW_S",       "nRTW_L",     "nRTW_S_L", "nRTW_L_L", "nWCK2DQO",
               "nRPST",  "nODTLon", "nODTon_min", "nFAW",         "nRFC",       "nREFI",    "nWCKPST",  "nCAS",
               "nAAD",   "nCS",     "tCK_ps",     "nPIM_MAC_LAT", "nPIM_MAC_II"});

    // Static spec data
    internal_prefetch_size = 16;
    init_states = {
        State::N_A,     // Channel
        State::PIM_SB,  // Rank
        State::N_A,     // BankGroup
        State::Closed,  // Bank
        State::Closed,  // Row
        State::N_A,     // Column
    };
    supported_requests = {
        Command::RD_S,        // Read -> RD_S
        Command::WR_S,        // Write -> WR_S
        Command::PIM_MAC,     // PIMCompute -> PIM_MAC
        Command::PIM_BCAST,   // PIMLoadAll -> PIM_BCAST
        Command::PIM_MAC_AB,  // PIMComputeAll -> PIM_MAC_AB
    };

    // Runtime config (organization, timing values, timing constraints)
    load_config(config);

    // Command handlers (function pointers, metadata, bank targets)
    populate_commands(CommandImpls{}, *this);
  }
};

// Self-registration
static bool _dram_lpddr6pim = DRAMSpec::register_standard(
    "LPDDR6PIM", [](const ConfigNode& config) { return std::make_unique<LPDDR6PIM>(config); });

}  // namespace Ramulator
