/******************************************************************************
 * AUTO-GENERATED FILE — DO NOT EDIT
 *
 * Generated by: python -m ramulator codegen
 * Source:       python/ramulator/dram/lpddr6pim.py
 *
 * Regenerate:   python -m ramulator codegen LPDDR6PIM
 ******************************************************************************/
#include "ramulator/dram/dram_spec.h"

#include "ramulator/dram/commands/populate.h"
#include "ramulator/dram/commands/ACT1.h"
#include "ramulator/dram/commands/ACT2.h"
#include "ramulator/dram/commands/CAS.h"
#include "ramulator/dram/commands/HAB.h"
#include "ramulator/dram/commands/HAB_PIM.h"
#include "ramulator/dram/commands/PIM_BCAST.h"
#include "ramulator/dram/commands/PIM_MAC.h"
#include "ramulator/dram/commands/PIM_MAC_AB.h"
#include "ramulator/dram/commands/PREab.h"
#include "ramulator/dram/commands/PREpb.h"
#include "ramulator/dram/commands/RDA_L.h"
#include "ramulator/dram/commands/RDA_S.h"
#include "ramulator/dram/commands/RD_L.h"
#include "ramulator/dram/commands/RD_S.h"
#include "ramulator/dram/commands/REFab.h"
#include "ramulator/dram/commands/SB.h"
#include "ramulator/dram/commands/WRA_L.h"
#include "ramulator/dram/commands/WRA_S.h"
#include "ramulator/dram/commands/WR_L.h"
#include "ramulator/dram/commands/WR_S.h"
#include "ramulator/dram/lambdas.h"
#include <fmt/format.h>

namespace Ramulator {

class LPDDR6PIM : public DRAMSpec {
 public:
  struct Level {
    enum : int { Channel, Rank, BankGroup, Bank, Row, Column, COUNT };
  };
  struct Command {
    enum : int { ACT1, ACT2, PREpb, PREab, CAS, RD_S, WR_S, RDA_S, WRA_S, RD_L, WR_L, RDA_L, WRA_L, REFab, SB, HAB, HAB_PIM, PIM_BCAST, PIM_MAC, PIM_MAC_AB, COUNT };
  };
  struct State {
    enum : int { Opened, Closed, Activating, N_A, PIM_SB, PIM_HAB, PIM_HAB_PIM, COUNT };
  };
  struct Timing {
    enum : int {
    rate, nBL_min, nBL_max, nBL_min_L, nBL_max_L, nRL, nWL, nACU, nRCDr, nRCDw, nRP, nRPab, nRAS, nRC, nWTP, nRTP,
    nRTP_L, nPPD, nCCDS, nCCDL, nCCDL_L, nCCDS_WR, nCCDL_WR, nCCDL_WR_L, nRRD, nWTRS, nWTRL, nRTW_S, nRTW_L,
    nRTW_S_L, nRTW_L_L, nWCK2DQO, nRPST, nODTLon, nODTon_min, nFAW, nRFC, nREFI, nWCKPST, nCAS, nAAD, nCS, tCK_ps,
    nPIM_MAC_LAT, nPIM_MAC_II, COUNT
    };
  };

  struct PowerCommand {
    enum : int { ACT, PRE, RD_S, RD_L, WR_S, WR_L, REF, COUNT };
  };

  using CommandImpls = std::tuple<
      Cmd::ACT1<LPDDR6PIM>, Cmd::ACT2<LPDDR6PIM>, Cmd::PREpb<LPDDR6PIM>, Cmd::PREab<LPDDR6PIM>, Cmd::CAS<LPDDR6PIM>,
      Cmd::RD_S<LPDDR6PIM>, Cmd::WR_S<LPDDR6PIM>, Cmd::RDA_S<LPDDR6PIM>, Cmd::WRA_S<LPDDR6PIM>, Cmd::RD_L<LPDDR6PIM>,
      Cmd::WR_L<LPDDR6PIM>, Cmd::RDA_L<LPDDR6PIM>, Cmd::WRA_L<LPDDR6PIM>, Cmd::REFab<LPDDR6PIM>, Cmd::SB<LPDDR6PIM>,
      Cmd::HAB<LPDDR6PIM>, Cmd::HAB_PIM<LPDDR6PIM>, Cmd::PIM_BCAST<LPDDR6PIM>, Cmd::PIM_MAC<LPDDR6PIM>,
      Cmd::PIM_MAC_AB<LPDDR6PIM>
  >;

  LPDDR6PIM(const ConfigNode& config) {
    // Counts
    level_count = Level::COUNT;
    command_count = Command::COUNT;
    state_count = State::COUNT;
    timing_count = Timing::COUNT;

    // String name maps + reverse lookup vectors
    set_names(levels, level_names, {"Channel", "Rank", "BankGroup", "Bank", "Row", "Column"});
    set_names(commands, command_names, {"ACT1", "ACT2", "PREpb", "PREab", "CAS", "RD_S", "WR_S", "RDA_S", "WRA_S", "RD_L", "WR_L", "RDA_L", "WRA_L", "REFab", "SB", "HAB", "HAB_PIM", "PIM_BCAST", "PIM_MAC", "PIM_MAC_AB"});
    set_names(states, state_names, {"Opened", "Closed", "Activating", "N_A", "PIM_SB", "PIM_HAB", "PIM_HAB_PIM"});
    set_names(timings, timing_names, {
        "rate", "nBL_min", "nBL_max", "nBL_min_L", "nBL_max_L", "nRL", "nWL", "nACU", "nRCDr", "nRCDw", "nRP",
        "nRPab", "nRAS", "nRC", "nWTP", "nRTP", "nRTP_L", "nPPD", "nCCDS", "nCCDL", "nCCDL_L", "nCCDS_WR",
        "nCCDL_WR", "nCCDL_WR_L", "nRRD", "nWTRS", "nWTRL", "nRTW_S", "nRTW_L", "nRTW_S_L", "nRTW_L_L", "nWCK2DQO",
        "nRPST", "nODTLon", "nODTon_min", "nFAW", "nRFC", "nREFI", "nWCKPST", "nCAS", "nAAD", "nCS", "tCK_ps",
        "nPIM_MAC_LAT", "nPIM_MAC_II"
    });

    // Static spec data
    internal_prefetch_size = 16;
    init_states = {
        State::N_A,           // Channel
        State::PIM_SB,        // Rank
        State::N_A,           // BankGroup
        State::Closed,        // Bank
        State::Closed,        // Row
        State::N_A,           // Column
    };
    supported_requests = {
        Command::RD_S,      // Read -> RD_S
        Command::WR_S,      // Write -> WR_S
        Command::PIM_MAC,   // PIMCompute -> PIM_MAC
        Command::PIM_BCAST, // PIMLoadAll -> PIM_BCAST
        Command::PIM_MAC_AB, // PIMComputeAll -> PIM_MAC_AB
    };

    // Runtime config (organization, timing values, timing constraints)
    load_config(config);

    // Command handlers (function pointers, metadata, bank targets)
    populate_commands(CommandImpls{}, *this);
    set_powers();
  }


  void set_powers() {
    if (!drampower_enable) return;

    if (!power_params.count("VDD1")) throw std::runtime_error("LPDDR6PIM: missing required power field VDD1");
    if (!power_params.count("VDD2C")) throw std::runtime_error("LPDDR6PIM: missing required power field VDD2C");
    if (!power_params.count("VDD2D")) throw std::runtime_error("LPDDR6PIM: missing required power field VDD2D");
    if (!power_params.count("IDD01")) throw std::runtime_error("LPDDR6PIM: missing required power field IDD01");
    if (!power_params.count("IDD02C")) throw std::runtime_error("LPDDR6PIM: missing required power field IDD02C");
    if (!power_params.count("IDD02D")) throw std::runtime_error("LPDDR6PIM: missing required power field IDD02D");
    if (!power_params.count("IDD2N1")) throw std::runtime_error("LPDDR6PIM: missing required power field IDD2N1");
    if (!power_params.count("IDD2N2C")) throw std::runtime_error("LPDDR6PIM: missing required power field IDD2N2C");
    if (!power_params.count("IDD2N2D")) throw std::runtime_error("LPDDR6PIM: missing required power field IDD2N2D");
    if (!power_params.count("IDD3N1")) throw std::runtime_error("LPDDR6PIM: missing required power field IDD3N1");
    if (!power_params.count("IDD3N2C")) throw std::runtime_error("LPDDR6PIM: missing required power field IDD3N2C");
    if (!power_params.count("IDD3N2D")) throw std::runtime_error("LPDDR6PIM: missing required power field IDD3N2D");
    if (!power_params.count("IDD4R1")) throw std::runtime_error("LPDDR6PIM: missing required power field IDD4R1");
    if (!power_params.count("IDD4R2C")) throw std::runtime_error("LPDDR6PIM: missing required power field IDD4R2C");
    if (!power_params.count("IDD4R2D")) throw std::runtime_error("LPDDR6PIM: missing required power field IDD4R2D");
    if (!power_params.count("IDD4W1")) throw std::runtime_error("LPDDR6PIM: missing required power field IDD4W1");
    if (!power_params.count("IDD4W2C")) throw std::runtime_error("LPDDR6PIM: missing required power field IDD4W2C");
    if (!power_params.count("IDD4W2D")) throw std::runtime_error("LPDDR6PIM: missing required power field IDD4W2D");
    if (!power_params.count("IDD51")) throw std::runtime_error("LPDDR6PIM: missing required power field IDD51");
    if (!power_params.count("IDD52C")) throw std::runtime_error("LPDDR6PIM: missing required power field IDD52C");
    if (!power_params.count("IDD52D")) throw std::runtime_error("LPDDR6PIM: missing required power field IDD52D");

    int num_ranks = organization.level_sizes[Level::Rank];
    power_stats.resize(num_ranks);
    for (int rank_id = 0; rank_id < num_ranks; rank_id++) {
      power_stats[rank_id].rank_id = rank_id;
      power_stats[rank_id].command_counters.resize(PowerCommand::COUNT, 0);
      power_stats[rank_id].incremental_command_counters.resize(command_count, 0);
      power_stats[rank_id].last_update_clk = 0;
    }

    powers.resize(level_count, std::vector<PowerFunc_t>(command_count, nullptr));
    powers[Level::Bank][Command::ACT2] = Lambdas::Power::Bank::ACT<LPDDR6PIM>;
    powers[Level::Bank][Command::PREpb] = Lambdas::Power::Bank::PRE<LPDDR6PIM>;
    powers[Level::Bank][Command::RD_S] = Lambdas::Power::Bank::RD_S<LPDDR6PIM>;
    powers[Level::Bank][Command::RDA_S] = Lambdas::Power::Bank::RD_S<LPDDR6PIM>;
    powers[Level::Bank][Command::RD_L] = Lambdas::Power::Bank::RD_L<LPDDR6PIM>;
    powers[Level::Bank][Command::RDA_L] = Lambdas::Power::Bank::RD_L<LPDDR6PIM>;
    powers[Level::Bank][Command::WR_S] = Lambdas::Power::Bank::WR_S<LPDDR6PIM>;
    powers[Level::Bank][Command::WRA_S] = Lambdas::Power::Bank::WR_S<LPDDR6PIM>;
    powers[Level::Bank][Command::WR_L] = Lambdas::Power::Bank::WR_L<LPDDR6PIM>;
    powers[Level::Bank][Command::WRA_L] = Lambdas::Power::Bank::WR_L<LPDDR6PIM>;
    powers[Level::Rank][Command::ACT2] = Lambdas::Power::Rank::ACT<LPDDR6PIM>;
    powers[Level::Rank][Command::PREpb] = Lambdas::Power::Rank::PRE<LPDDR6PIM>;
    powers[Level::Rank][Command::PREab] = Lambdas::Power::Rank::PREA<LPDDR6PIM>;
    powers[Level::Rank][Command::REFab] = Lambdas::Power::Rank::REFab<LPDDR6PIM>;
    powers_incremental.resize(level_count, std::vector<PowerFunc_t>(command_count, nullptr));
    powers_incremental[Level::Rank][Command::PIM_MAC] = Lambdas::Power::Rank::COUNT_PIM_INCREMENTAL_ENERGY<LPDDR6PIM>;
    powers_incremental[Level::Rank][Command::PIM_MAC_AB] = Lambdas::Power::Rank::COUNT_PIM_INCREMENTAL_ENERGY<LPDDR6PIM>;
    powers_incremental[Level::Rank][Command::PIM_BCAST] = Lambdas::Power::Rank::COUNT_PIM_INCREMENTAL_ENERGY<LPDDR6PIM>;
    powers_incremental[Level::Rank][Command::HAB] = Lambdas::Power::Rank::COUNT_PIM_INCREMENTAL_ENERGY<LPDDR6PIM>;
    powers_incremental[Level::Rank][Command::HAB_PIM] = Lambdas::Power::Rank::COUNT_PIM_INCREMENTAL_ENERGY<LPDDR6PIM>;
    powers_incremental[Level::Rank][Command::SB] = Lambdas::Power::Rank::COUNT_PIM_INCREMENTAL_ENERGY<LPDDR6PIM>;
  }

  void register_power_stats(Stats& stats) override {
    if (!drampower_enable) return;
    stats.add("total_background_energy", total_background_energy_pJ);
    stats.add("total_cmd_energy", total_cmd_energy_pJ);
    stats.add("total_energy", total_energy_pJ);
    stats.add("total_incremental_cmd_energy", total_incremental_cmd_energy_pJ);
    for (auto& power_stat : power_stats) {
      stats.add(fmt::format("total_background_energy_rank_{}", power_stat.rank_id), power_stat.background_active_energy_pJ + power_stat.background_idle_energy_pJ);
      stats.add(fmt::format("total_cmd_energy_rank_{}", power_stat.rank_id), power_stat.command_energy_pJ);
      stats.add(fmt::format("total_energy_rank_{}", power_stat.rank_id), power_stat.total_energy_pJ);
      stats.add(fmt::format("total_incremental_cmd_energy_rank_{}", power_stat.rank_id),
                power_stat.incremental_command_energy_pJ);
      stats.add(fmt::format("background_active_energy_rank_{}", power_stat.rank_id), power_stat.background_active_energy_pJ);
      stats.add(fmt::format("background_idle_energy_rank_{}", power_stat.rank_id), power_stat.background_idle_energy_pJ);
      stats.add(fmt::format("active_cycles_rank_{}", power_stat.rank_id), power_stat.active_cycles);
      stats.add(fmt::format("idle_cycles_rank_{}", power_stat.rank_id), power_stat.idle_cycles);
    }
  }

  void finalize_power(Clk_t clk, DRAMNode* root) override {
    if (!drampower_enable || root == nullptr) return;
    total_background_energy_pJ = 0.0;
    total_cmd_energy_pJ = 0.0;
    total_energy_pJ = 0.0;
    total_incremental_cmd_energy_pJ = 0.0;
    for (auto& rank_node : root->m_child_nodes) {
      process_rank_energy(power_stats[rank_node->m_node_id], rank_node.get(), clk);
    }
  }

  void process_rank_energy(DRAMPowerStats& rank_stats, DRAMNode* rank_node, Clk_t clk) {
    Lambdas::Power::Rank::finalize_rank<LPDDR6PIM>(rank_node, clk);
    double tCK_ns = static_cast<double>(timing_vals[Timing::tCK_ps]) / 1000.0;
    rank_stats.background_active_energy_pJ = ((power_params.at("VDD1") * power_params.at("IDD3N1")) + (power_params.at("VDD2C") * power_params.at("IDD3N2C")) + (power_params.at("VDD2D") * power_params.at("IDD3N2D"))) * rank_stats.active_cycles * tCK_ns;
    rank_stats.background_idle_energy_pJ = ((power_params.at("VDD1") * power_params.at("IDD2N1")) + (power_params.at("VDD2C") * power_params.at("IDD2N2C")) + (power_params.at("VDD2D") * power_params.at("IDD2N2D"))) * rank_stats.idle_cycles * tCK_ns;
    double act_cmd_energy = ((power_params.at("VDD1") * (power_params.at("IDD01") - power_params.at("IDD3N1"))) + (power_params.at("VDD2C") * (power_params.at("IDD02C") - power_params.at("IDD3N2C"))) + (power_params.at("VDD2D") * (power_params.at("IDD02D") - power_params.at("IDD3N2D")))) * rank_stats.command_counters[PowerCommand::ACT] * timing_vals[Timing::nRAS] * tCK_ns;
    double pre_cmd_energy = ((power_params.at("VDD1") * (power_params.at("IDD01") - power_params.at("IDD2N1"))) + (power_params.at("VDD2C") * (power_params.at("IDD02C") - power_params.at("IDD2N2C"))) + (power_params.at("VDD2D") * (power_params.at("IDD02D") - power_params.at("IDD2N2D")))) * rank_stats.command_counters[PowerCommand::PRE] * timing_vals[Timing::nRP] * tCK_ns;
    double rd_s_cmd_energy = ((power_params.at("VDD1") * (power_params.at("IDD4R1") - power_params.at("IDD3N1"))) + (power_params.at("VDD2C") * (power_params.at("IDD4R2C") - power_params.at("IDD3N2C"))) + (power_params.at("VDD2D") * (power_params.at("IDD4R2D") - power_params.at("IDD3N2D")))) * rank_stats.command_counters[PowerCommand::RD_S] * timing_vals[Timing::nBL_min] * tCK_ns;
    double rd_l_cmd_energy = ((power_params.at("VDD1") * (power_params.at("IDD4R1") - power_params.at("IDD3N1"))) + (power_params.at("VDD2C") * (power_params.at("IDD4R2C") - power_params.at("IDD3N2C"))) + (power_params.at("VDD2D") * (power_params.at("IDD4R2D") - power_params.at("IDD3N2D")))) * rank_stats.command_counters[PowerCommand::RD_L] * timing_vals[Timing::nBL_min_L] * tCK_ns;
    double wr_s_cmd_energy = ((power_params.at("VDD1") * (power_params.at("IDD4W1") - power_params.at("IDD3N1"))) + (power_params.at("VDD2C") * (power_params.at("IDD4W2C") - power_params.at("IDD3N2C"))) + (power_params.at("VDD2D") * (power_params.at("IDD4W2D") - power_params.at("IDD3N2D")))) * rank_stats.command_counters[PowerCommand::WR_S] * timing_vals[Timing::nBL_min] * tCK_ns;
    double wr_l_cmd_energy = ((power_params.at("VDD1") * (power_params.at("IDD4W1") - power_params.at("IDD3N1"))) + (power_params.at("VDD2C") * (power_params.at("IDD4W2C") - power_params.at("IDD3N2C"))) + (power_params.at("VDD2D") * (power_params.at("IDD4W2D") - power_params.at("IDD3N2D")))) * rank_stats.command_counters[PowerCommand::WR_L] * timing_vals[Timing::nBL_min_L] * tCK_ns;
    double ref_cmd_energy = ((power_params.at("VDD1") * power_params.at("IDD51")) + (power_params.at("VDD2C") * power_params.at("IDD52C")) + (power_params.at("VDD2D") * power_params.at("IDD52D"))) * rank_stats.command_counters[PowerCommand::REF] * timing_vals[Timing::nRFC] * tCK_ns;
    rank_stats.command_energy_pJ = act_cmd_energy +
        pre_cmd_energy +
        rd_s_cmd_energy +
        rd_l_cmd_energy +
        wr_s_cmd_energy +
        wr_l_cmd_energy +
        ref_cmd_energy;
    rank_stats.total_energy_pJ = rank_stats.background_active_energy_pJ + rank_stats.background_idle_energy_pJ + rank_stats.command_energy_pJ;
    total_background_energy_pJ += rank_stats.background_active_energy_pJ + rank_stats.background_idle_energy_pJ;
    total_cmd_energy_pJ += rank_stats.command_energy_pJ;
    total_energy_pJ += rank_stats.total_energy_pJ;

    double pim_mac_incremental_cmd_energy = rank_stats.incremental_command_counters[Command::PIM_MAC] * (pim_array_local_energy_pJ + pim_lanes * pim_compute_energy_pJ_per_mac + pim_cell_to_pim_energy_pJ_per_256b + pim_vrf_access_energy_pJ + pim_srf_access_energy_pJ);
    double pim_mac_ab_incremental_cmd_energy = rank_stats.incremental_command_counters[Command::PIM_MAC_AB] * (pim_array_local_energy_pJ + pim_lanes * pim_compute_energy_pJ_per_mac + pim_cell_to_pim_energy_pJ_per_256b + pim_vrf_access_energy_pJ + pim_srf_access_energy_pJ);
    double pim_bcast_incremental_cmd_energy = ((power_params.at("VDD1") * (power_params.at("IDD01") - power_params.at("IDD2N1"))) + (power_params.at("VDD2C") * (power_params.at("IDD02C") - power_params.at("IDD2N2C"))) + (power_params.at("VDD2D") * (power_params.at("IDD02D") - power_params.at("IDD2N2D")))) * rank_stats.incremental_command_counters[Command::PIM_BCAST] * timing_vals[Timing::nBL_min] * tCK_ns + rank_stats.incremental_command_counters[Command::PIM_BCAST] * (pim_cell_to_pim_energy_pJ_per_256b);
    double hab_incremental_cmd_energy = ((power_params.at("VDD1") * (power_params.at("IDD01") - power_params.at("IDD2N1"))) + (power_params.at("VDD2C") * (power_params.at("IDD02C") - power_params.at("IDD2N2C"))) + (power_params.at("VDD2D") * (power_params.at("IDD02D") - power_params.at("IDD2N2D")))) * rank_stats.incremental_command_counters[Command::HAB] * timing_vals[Timing::nBL_min] * tCK_ns + rank_stats.incremental_command_counters[Command::HAB] * (pim_mode_switch_energy_pJ);
    double hab_pim_incremental_cmd_energy = ((power_params.at("VDD1") * (power_params.at("IDD01") - power_params.at("IDD2N1"))) + (power_params.at("VDD2C") * (power_params.at("IDD02C") - power_params.at("IDD2N2C"))) + (power_params.at("VDD2D") * (power_params.at("IDD02D") - power_params.at("IDD2N2D")))) * rank_stats.incremental_command_counters[Command::HAB_PIM] * timing_vals[Timing::nBL_min] * tCK_ns + rank_stats.incremental_command_counters[Command::HAB_PIM] * (pim_mode_switch_energy_pJ);
    double sb_incremental_cmd_energy = ((power_params.at("VDD1") * (power_params.at("IDD01") - power_params.at("IDD2N1"))) + (power_params.at("VDD2C") * (power_params.at("IDD02C") - power_params.at("IDD2N2C"))) + (power_params.at("VDD2D") * (power_params.at("IDD02D") - power_params.at("IDD2N2D")))) * rank_stats.incremental_command_counters[Command::SB] * timing_vals[Timing::nBL_min] * tCK_ns + rank_stats.incremental_command_counters[Command::SB] * (pim_mode_switch_energy_pJ);
    rank_stats.incremental_command_energy_pJ = pim_mac_incremental_cmd_energy +
        pim_mac_ab_incremental_cmd_energy +
        pim_bcast_incremental_cmd_energy +
        hab_incremental_cmd_energy +
        hab_pim_incremental_cmd_energy +
        sb_incremental_cmd_energy;
    total_incremental_cmd_energy_pJ += rank_stats.incremental_command_energy_pJ;
  }

  double total_incremental_cmd_energy_pJ = 0.0;
};

// Self-registration
static bool _dram_lpddr6pim = DRAMSpec::register_standard(
    "LPDDR6PIM", [](const ConfigNode& config) { return std::make_unique<LPDDR6PIM>(config); });

}  // namespace Ramulator
