###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/frontend/impl/memory_trace/lpddr5_pim_concrete_trace.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param


class LPDDR5PIMConcreteTrace(Component):
    impl = "LPDDR5PIMConcreteTrace"
    clock_ratio = Param(int, required=True, cpp_type="unsigned int")
    path = Param(str, required=True)
    pim_compute_request_type_id = Param(int, required=True)
    pim_load_all_request_type_id = Param(int, required=True)
    pim_compute_all_request_type_id = Param(int, required=True)
    sb_command_id = Param(int, required=True)
    hab_command_id = Param(int, required=True)
    hab_pim_command_id = Param(int, required=True)
    addr_vec_size = Param(int, required=True)
    max_trace_bytes = Param(int, default=1073741824)
    max_records = Param(int, default=1000000)
    max_repeat = Param(int, default=1000000)
    max_expanded_records = Param(int, default=1000000000)
