###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/frontend/impl/memory_trace/structured_workload_surrogate_trace.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param


class StructuredWorkloadSurrogateTrace(Component):
    impl = "StructuredWorkloadSurrogateTrace"
    clock_ratio = Param(int, required=True, cpp_type="unsigned int")
    path = Param(str, required=True)
    pim_request_type_id = Param(int, required=True)
    pim_load_request_type_id = Param(int, default=-1)
    pim_compute_all_request_type_id = Param(int, default=-1)
    addr_vec_size = Param(int, required=True)
    total_bank_units = Param(int, required=True)
    row_pos = Param(int, required=True)
    col_pos = Param(int, required=True)
    num_rows = Param(int, required=True)
    num_cols = Param(int, required=True)
    bank_positions = Param(list, required=True, cpp_type="std::vector<int>")
    bank_counts = Param(list, required=True, cpp_type="std::vector<int>")
