import importlib

ramulator = importlib.import_module("ramulator")

DATATYPE_CAPABILITY_MATRIX = {
    "int8": {
        "kind": "integer class",
        "status": "modeled baseline",
        "scope": "config-only framing",
        "behavior": "no datatype-specific timing or slot behavior change",
    },
    "int16": {
        "kind": "integer class",
        "status": "derived contrast",
        "scope": "assumption-only framing",
        "behavior": "no datatype-specific timing or slot behavior change",
    },
    "fp16": {
        "kind": "floating-point class",
        "status": "assumed contrast",
        "scope": "config-only framing",
        "behavior": "no datatype-specific timing or slot behavior change",
    },
}

CONFIG = dict(
    dram_class="LPDDR5PIM",
    org_preset="LPDDR5_8Gb_x16",
    timing_preset="LPDDR5_6400",
    dram_kwargs=dict(
        pim_enabled=True,
        pim_mode="bank",
        pim_blocks_per_bank=1,
        pim_datatype="int8",
        pim_datatype_class="int8",
    ),
    datatype_capability_matrix=DATATYPE_CAPABILITY_MATRIX,
    controller_class="LPDDR5PIM",
    fast_ctrl_extra_kwargs=dict(
        refresh_manager=ramulator.refresh_manager.NoRefresh(),
    ),
    full_ctrl_extra_kwargs=dict(
        refresh_manager=ramulator.refresh_manager.AllBank(scope="Rank"),
    ),
    full_streaming_requests=1_000_000,
    frontend_clock_ratio=4,
    stream_cols=8,
    pim_mode=True,
    num_pim_requests=4096,
    pim_distribution_mode="same_bank",
    pim_same_bank=True,
    pim_dependency_count=1,
    pim_bank_group_size=4,
    pim_bank_sequence=[],
    pim_burst_length=16,
    pim_row_start=0,
    pim_row_count=1,
    pim_split_all_bank=False,
    dependency_patterns=dict(
        same_bank_dependent=dict(
            dram_kwargs=dict(
                pim_enabled=True,
                pim_mode="bank",
                pim_blocks_per_bank=2,
                pim_datatype="int8",
                pim_datatype_class="int8",
            ),
            pim_distribution_mode="same_bank",
            pim_same_bank=True,
            pim_dependency_count=1,
            pim_bank_sequence=[],
            pim_row_start=0,
            pim_row_count=1,
        ),
        same_bank_independent=dict(
            dram_kwargs=dict(
                pim_enabled=True,
                pim_mode="bank",
                pim_blocks_per_bank=2,
                pim_datatype="int8",
                pim_datatype_class="fp16",
            ),
            pim_distribution_mode="same_bank",
            pim_same_bank=True,
            pim_dependency_count=2,
            pim_bank_sequence=[],
            pim_row_start=0,
            pim_row_count=1,
        ),
        bounded_bank_group_round_robin=dict(
            dram_kwargs=dict(
                pim_enabled=True,
                pim_mode="bank",
                pim_blocks_per_bank=2,
                pim_datatype="int8",
            ),
            pim_distribution_mode="bank_sequence",
            pim_same_bank=False,
            pim_bank_sequence=[0, 1, 2, 3],
            pim_bank_group_size=4,
            pim_dependency_count=2,
            pim_burst_length=8,
            pim_row_start=0,
            pim_row_count=2,
        ),
        bounded_bank_group_round_robin_1block=dict(
            dram_kwargs=dict(
                pim_enabled=True,
                pim_mode="bank",
                pim_blocks_per_bank=1,
                pim_datatype="int8",
            ),
            pim_distribution_mode="bank_sequence",
            pim_same_bank=False,
            pim_bank_sequence=[0, 1, 2, 3],
            pim_bank_group_size=4,
            pim_dependency_count=1,
            pim_burst_length=8,
            pim_row_start=0,
            pim_row_count=1,
        ),
        # Controlled case set for explicit bank-count / blocks-per-bank comparisons.
        explicit_bank_count_cases=dict(
            single_bank_1block=dict(
                dram_kwargs=dict(
                    pim_enabled=True,
                    pim_mode="bank",
                    pim_blocks_per_bank=1,
                    pim_datatype="int8",
                ),
                pim_distribution_mode="same_bank",
                pim_same_bank=True,
                pim_dependency_count=2,
                pim_bank_sequence=[],
                pim_row_start=0,
                pim_row_count=1,
            ),
            single_bank_2block=dict(
                dram_kwargs=dict(
                    pim_enabled=True,
                    pim_mode="bank",
                    pim_blocks_per_bank=2,
                    pim_datatype="int8",
                ),
                pim_distribution_mode="same_bank",
                pim_same_bank=True,
                pim_dependency_count=2,
                pim_bank_sequence=[],
                pim_row_start=0,
                pim_row_count=1,
            ),
            rr_2bank_1block=dict(
                dram_kwargs=dict(
                    pim_enabled=True,
                    pim_mode="bank",
                    pim_blocks_per_bank=1,
                    pim_datatype="int8",
                ),
                pim_distribution_mode="bank_sequence",
                pim_same_bank=False,
                pim_bank_sequence=[0, 1],
                pim_bank_group_size=2,
                pim_dependency_count=2,
                pim_burst_length=8,
                pim_row_start=0,
                pim_row_count=1,
            ),
            rr_2bank_2block=dict(
                dram_kwargs=dict(
                    pim_enabled=True,
                    pim_mode="bank",
                    pim_blocks_per_bank=2,
                    pim_datatype="int8",
                ),
                pim_distribution_mode="bank_sequence",
                pim_same_bank=False,
                pim_bank_sequence=[0, 1],
                pim_bank_group_size=2,
                pim_dependency_count=2,
                pim_burst_length=8,
                pim_row_start=0,
                pim_row_count=1,
            ),
            rr_4bank_1block=dict(
                dram_kwargs=dict(
                    pim_enabled=True,
                    pim_mode="bank",
                    pim_blocks_per_bank=1,
                    pim_datatype="int8",
                ),
                pim_distribution_mode="bank_sequence",
                pim_same_bank=False,
                pim_bank_sequence=[0, 1, 2, 3],
                pim_bank_group_size=4,
                pim_dependency_count=2,
                pim_burst_length=8,
                pim_row_start=0,
                pim_row_count=1,
            ),
            rr_4bank_2block=dict(
                dram_kwargs=dict(
                    pim_enabled=True,
                    pim_mode="bank",
                    pim_blocks_per_bank=2,
                    pim_datatype="int8",
                ),
                pim_distribution_mode="bank_sequence",
                pim_same_bank=False,
                pim_bank_sequence=[0, 1, 2, 3],
                pim_bank_group_size=4,
                pim_dependency_count=2,
                pim_burst_length=8,
                pim_row_start=0,
                pim_row_count=1,
            ),
            rr_8bank_1block=dict(
                dram_kwargs=dict(
                    pim_enabled=True,
                    pim_mode="bank",
                    pim_blocks_per_bank=1,
                    pim_datatype="int8",
                ),
                pim_distribution_mode="bank_sequence",
                pim_same_bank=False,
                pim_bank_sequence=[0, 1, 2, 3, 4, 5, 6, 7],
                pim_bank_group_size=8,
                pim_dependency_count=2,
                pim_burst_length=8,
                pim_row_start=0,
                pim_row_count=1,
            ),
            rr_8bank_2block=dict(
                dram_kwargs=dict(
                    pim_enabled=True,
                    pim_mode="bank",
                    pim_blocks_per_bank=2,
                    pim_datatype="int8",
                ),
                pim_distribution_mode="bank_sequence",
                pim_same_bank=False,
                pim_bank_sequence=[0, 1, 2, 3, 4, 5, 6, 7],
                pim_bank_group_size=8,
                pim_dependency_count=2,
                pim_burst_length=8,
                pim_row_start=0,
                pim_row_count=1,
            ),
        ),
        # Bounded partial subsequence: only banks [0, 2] in the bank group.
        # Tests that the frontend can target a strict subset of the bank group,
        # exercising cross-bank-group timing (tCCD_S) without covering all 4 banks.
        bounded_partial_subsequence=dict(
            dram_kwargs=dict(
                pim_enabled=True,
                pim_mode="bank",
                pim_blocks_per_bank=2,
                pim_datatype="int8",
            ),
            pim_distribution_mode="bank_sequence",
            pim_same_bank=False,
            pim_bank_sequence=[0, 2],
            pim_bank_group_size=4,
            pim_dependency_count=2,
            pim_burst_length=8,
            pim_row_start=0,
            pim_row_count=2,
        ),
        # Bounded repeated-bank subsequence: banks [0, 0, 1, 1] in the bank group.
        # Tests that the frontend can express repeated bank visits within one
        # distribution cycle, exercising same-bank-group burst behavior where
        # consecutive requests target the same bank before advancing.
        bounded_repeated_bank_subsequence=dict(
            dram_kwargs=dict(
                pim_enabled=True,
                pim_mode="bank",
                pim_blocks_per_bank=2,
                pim_datatype="int8",
            ),
            pim_distribution_mode="bank_sequence",
            pim_same_bank=False,
            pim_bank_sequence=[0, 0, 1, 1],
            pim_bank_group_size=4,
            pim_dependency_count=2,
            pim_burst_length=8,
            pim_row_start=0,
            pim_row_count=2,
        ),
        all_bank_split_mode=dict(
            dram_kwargs=dict(
                pim_enabled=True,
                pim_mode="bank",
                pim_blocks_per_bank=1,
                pim_datatype="int8",
            ),
            pim_distribution_mode="same_bank",
            pim_same_bank=True,
            pim_dependency_count=1,
            pim_bank_sequence=[],
            pim_bank_group_size=4,
            pim_burst_length=1,
            pim_row_start=0,
            pim_row_count=1,
            pim_split_all_bank=True,
        ),
    ),
    dependency_pattern_nop_counters=[
        # Saturation anchors (very low NOP)
        1, 2, 3,
        # Dense in transition region (5-50)
        5, 6, 8, 10, 12, 15, 18, 20, 25, 30, 35, 40, 50,
        # Unloaded anchor (high NOP)
        75, 100,
    ],
    nop_counters=[
        1,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        20,
        30,
        50,
        100,
        1000,
        2000,
        5000,
        10000,
    ],
)
